### ISSUE TITLE
Improvements to main screen

### ISSUE THREAD

**Issue by urzds** [privacyidea/privacyidea-authenticator#28]
FreeOTP has a main screen, that could service as an example on how to make it easy for users to find the desired information: The issuer name stands out in bold on the left, while the generated code stands out on the right, the details (account name, description) are smaller below that. This makes it easy and fast to scan the list for the correct account by looking at the issuers on the left side. Afterwards the eyes can "switch over" to the code at the right side. privacyIDEA Authenticator instead has the code standing out in bold at the top left, with the issuer and description in tiny letters below it. If I was scanning the list for a certain code instead of an account/issuer, this would be ideal.

**Comment by cornelinux** [comment]
I personally do not recommend to use a smartphone app on a bunch of different accounts, since it is not secure.
It also is not - as you pointed out - a great UX having a long list of accounts. Even with FreeOTP it sucks.

Our main use case is to have **one** account in the app. You will even be able to lock the app to only allow one account. When having only one account, it is better to have a big OTP value than a big account name.

@nilsbehlen What do you think? Can this be a customizing thing? I do not think so. But we might separated the issuer and the token name a bit different in the future. Currently it is only separated by a colon.

This is the great thing about open source and open standards like rfc6238 is, that you can choose and pick your favorite implementation. In addition, when I look at the current screen shots of the FreeOTP app in the play store, it looks like a **big** OTP value and a *bold* account name underneath.

@nilsbehlen I would recommend the close this issue, unless you have a great idea about this?

**Comment by cornelinux** [comment]
@urzds PS: The privacyIDEA Authenticator is mainly ment to work well with the privacyIDEA Server. In this  scenario the user auhenticates against privacyIDEA. The privacyIDEA server is located in his company. The user has one account and all applications are configured against the privacyIDEA server. Thus, the user will only have one profile in the app.

Of course you could use the app with all other services, but this is not our main goal, since we can not add any additional security if you are using the privacyIDEA authenticator with e.g. paypal. It does not matter, if a user would use a privacyIDEA authenticator or a Google authenticator or FreeOTP.

But in a scenario with privacyIDEA server, it very much matters, if the user uses a FreeOTP app and the secret can be easily stolen in the enrollment process of if the user uses the privacyIDEA authenticator and the secret can not be easily stolen.

**Comment by nilsbehlen** [comment]
Inside each row of the tokens list, we can customize everything (fonts+size,colors, even the separation of issuer : tokenID) pretty easily if we agree on how we put it in the URI.
But to customize the general layout of the list (e.g. to a grid pattern) would be alot more work.

I could maybe add a search bar at the top, for people with long token lists.

**Comment by cornelinux** [comment]
I very much discourage a thing like a searchbar. We should keep a **clean layout**. I do not want to encourage people and especially services to provide TOTP via QR Code.
There is no sense in providing this. There is a much better and safer solution with U2F, which we should encourage.

We might keep in mind changing the *general layout* for special customers. But as you pointed out, this is a lot of work and we should wait for the corresponding recommendations.

**Comment by urzds** [comment]
I also do not think a search bar would help, since I used privacyIDEA Authenticator and FreeOTP with only one hand, scrolling with the thumb through the accounts and typing the number on my computer keyboard with the other hand. Having to type something into a search bar would be so cumbersome, that I think it would only be used very seldomly by few people.
