### ISSUE TITLE
Application size

### ISSUE THREAD

**Issue by urzds** [privacyidea/privacyidea-authenticator#29]
The FreeOTP app (without user data) is about 1.5MiB large. privacyIDEA Authenticator comes at about 9MiB (without user data). Both serve the same purpose and have about the same feature set. Hence I would expect that it is possible to shrink privacyIDEA Authenticator to at least ⅓ of its current size without loosing features.

**Comment by cornelinux** [comment]
1. Why?
2. You are wrong:

privacyIDEA has a much bigger feature set:

* privacyIDEA authenticator supports HOTP tokens. FreeOTP does not.
* privacyIDEA authenticator supports locking tokens with a PIN. FreeOTP does not.
* privacyIDEA authenticator contains all license text. FreeOTP does not.
* privacyIDEA authenticator has enhanced support for additional features in the QR code like:
   * two step enrollment
   * PIN protecting tokens...

**Comment by nilsbehlen** [comment]
to be fair i left some images of older versions and some unused layouts and classes in the app.
I removed them now so you can check at the next release how the size was affected @urzds

**Comment by urzds** [comment]
Why:
* I am generally trying not to be wasteful with resources.
* I still own phones that have only a few hundred MiB of storage.
* I learned that the more code is contained in an app (especially bundled libraries where the authors might not have much control over) the bigger the attack surface, which seems generally inadvisable for a security app.

Thanks for the clarification regarding the feature set, it is very much appreciated.

[troll] If these features really need 7.5 MiB to be implemented correctly, I am also fully convinced. ;) [/troll]

@nilsbehlen Thanks! I will have another look.

**Comment by cornelinux** [comment]
@nilsbehlen thanks for removing the images.

But I still think this is comparing apples to oranges. FreeOTP is a smart but very feature limited app.
Well, if you take a look at the sloccount it turns out that the privacyIDEA authenticator comes with roughly 5 times the java code, not having looked very closely. But I guess the privacyIDEA authenticator has roughly five times the features?

One day the pi authenticator could be refactored - like every software. But not even _before_ the first version 1.0.

Look at what Donald Knuth says about premature optimization.

@urzds: Everything you are saying is right. But if you might not want to use a few hundred MiB phone - which probably has not the latest OS updates - for a security app! ;-)
